rBlog/config/routes.rb
Rails.application.routes.draw do
  get 'contact' => "contacts#new"

  get 'contacts/create'

  get 'about' => "about#index"

  namespace :admin do
  get 'sessions/new'
  end

  namespace :admin do
  get 'sessions/create'
  end

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
  get 'users/create'
  end

  namespace :admin do
  get 'users/edit'
  end

  namespace :admin do
  get 'users/update'
  end

  namespace :admin do
  get 'users/destroy'
  end

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'users/show'
  end

  namespace :admin do
  get 'comments/destroy'
  end

  get 'comments/new'

  namespace :admin do
  get 'categories/new'
  end

  namespace :admin do
  get 'categories/create'
  end

  namespace :admin do
  get 'categories/edit'
  end

  namespace :admin do
  get 'categories/update'
  end

  namespace :admin do
  get 'categories/destroy'
  end

  namespace :admin do
  get 'categories/index'
  end

  namespace :admin do
  get 'categories/show'
  end

  get 'categories/show'

  namespace :admin do
  get 'posts/new'
  end

  namespace :admin do
  get 'posts/create'
  end

  namespace :admin do
  get 'posts/edit'
  end

  namespace :admin do
  get 'posts/update'
  end

  namespace :admin do
  get 'posts/destroy'
  end

  namespace :admin do
  get 'posts/index'
  end

  namespace :admin do
  get 'posts/show'
  end

  get 'posts/index'

  get 'posts/show'

  resources :posts, :categories, :comments
  resources :contacts, only: [:new, :create]

  namespace :admin do
    resources :posts, :categories, :comments, :users
  end

  root 'posts#index'

end

rBlog/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts

  validates :name, presence: true
end

rBlog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

rBlog/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :users
  has_many :commnets

  validates :title,  presence: true
  validates :category_id, presence: true
  validates :body, presence: true
end

rBlog/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  
  has_many :posts

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password, confirmation: true

  def self.authentication(email, password)
    user = find_by_email(email)
    if user && user_password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

rBlog/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

rBlog/app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  def destroy
  end
end

rBlog/app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  def new
    @page_title = "Add Post"
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post Created"
      redirect_to admin_posts_path
    else
      render "new"
    end
  end

  def edit
    @page_title = "Edit Post"
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      flash[:notice] = "Post Updated"
      redirect_to admin_posts_path
    else
      render "new"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    flash[:notice] = "Post Removed"
    redirect_to admin_posts_path
  end

  def index
    @posts = Post.all
  end

  private

  def post_params
    params.require(:post).permit(:title, :category_id, :user_id, :tags, :img, :body)
  end
end

rBlog/app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::ApplicationController
  def new
  end

  def create
  end
end

rBlog/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def new
    @page_title = "Add User"
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User Created"
      redirect_to admin_users_path
    else
      render "new"
    end
  end

  def edit
    @page_title = "Edit User"
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "User Updated"
      redirect_to admin_users_path
    else
      render "new"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    flash[:notice] = "User Removed"
    redirect_to admin_users_path
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

rBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rBlog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  end
end

rBlog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end
end

rBlog/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

rBlog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end
end

rBlog/app/helpers/about_helper.rb
module AboutHelper
end

rBlog/app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

rBlog/app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

rBlog/app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

rBlog/app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

rBlog/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

rBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

rBlog/app/helpers/categories_helper.rb
module CategoriesHelper
end

rBlog/app/helpers/comments_helper.rb
module CommentsHelper
end

rBlog/app/helpers/contacts_helper.rb
module ContactsHelper
end

rBlog/app/helpers/posts_helper.rb
module PostsHelper
end

rBlog/app/views/admin/comments/destroy.html.erb
<h1>Admin::Comments#destroy</h1>
<p>Find me in app/views/admin/comments/destroy.html.erb</p>

rBlog/app/views/admin/posts/edit.html.erb
<h2><%= @page_title %></h2>

<%= form_for [:admin, @post] do | f | %>
  <!-- Check for errors -->
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do | msg | %>
      <!-- Show errors -->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
      <%= f.select :category_id, Category.all.collect { | x | [x.name, x.id]}, {:include_blank => "Select One"}, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.select :user_id, User.all.collect { | x | [x.name, x.id]}, {:include_blank => "Select One"}, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.label :tags %>
    <%= f.text_area :tags, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class:"form-control" %>
  </div>
  <br>
  <%= f.submit "Submit", class:"btn btn-primary" %>
  <%= link_to "Cancel", admin_posts_path, class:"btn btn-default" %>
<% end %>

rBlog/app/views/admin/posts/index.html.erb
<h2 class="page-header">Manage Posts <%= link_to "Create New", new_admin_post_path, class:"btn btn-success pull-right"%></h2>

<% if @posts.exists? %>
  <table class="table table-striped">
    <tr>
      <th>Post Title</th>
      <th>Create Date</th>
      <th>Actions</th>
    </tr>
    <% @posts.each do | post | %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
      <td><%= link_to "Edit", edit_admin_post_path(post), class:"btn btn-primary" %> <%= link_to "Delete", admin_post_path(post), class:"btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %></td> <!--make these buttons -->
    </tr>
  <% end %>
</table>
<% else %>
  <p>There are no posts</p>
<% end %>

rBlog/app/views/admin/posts/new.html.erb
<h2><%= @page_title %></h2>

<%= form_for [:admin, @post] do | f | %>
  <!-- Check for errors -->
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do | msg | %>
      <!-- Show errors -->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
      <%= f.select :category_id, Category.all.collect { | x | [x.name, x.id]}, {:include_blank => "Select One"}, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.select :user_id, User.all.collect { | x | [x.name, x.id]}, {:include_blank => "Select One"}, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.label :tags %>
    <%= f.text_area :tags, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class:"form-control" %>
  </div>
  <br>
  <%= f.submit "Submit", class:"btn btn-primary" %>
  <%= link_to "Cancel", admin_posts_path, class:"btn btn-default" %>
<% end %>

rBlog/app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

rBlog/app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="post">
      <img src='img/rails1.jpg'>
      <div class="post-content">
        <h3>Lorem Ipsum</h3>
        <small>Posted by Matt on October 24, 2014</small>
        <p>Proin sit amet lectus quis ex rutrum dictum vel ut purus. In placerat lacus a nisi imperdiet varius. Donec semper suscipit odio, hendrerit sollicitudin orci ullamcorper a. Integer ornare est sed velit consectetur, fringilla tempor urna auctor. Aliquam lobortis imperdiet leo eget tincidunt. Cras blandit dapibus urna, quis commodo eros semper ut. Fusce tempus odio non commodo faucibus. Nam mattis faucibus tellus, a cursus neque accumsan fringilla. Curabitur sagittis ex vel tincidunt fermentum. Cras congue augue non gravida varius. Maecenas tincidunt dapibus elit id vulputate. Integer fermentum in risus eu tincidunt. Phasellus metus libero, elementum non rhoncus at, condimentum sed est.</p>
        <a class="btn btn-primary btn-block">Read More</a>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="post">
      <img src='img/rails1.jpg'>
      <div class="post-content">
        <h3>Lorem Ipsum</h3>
        <small>Posted by Matt on October 24, 2014</small>
        <p>Praesent ut diam dolor. Nunc ornare id velit non sodales. Fusce volutpat ante ac interdum dignissim. Morbi id lorem dignissim libero egestas dignissim vel et ex. Donec interdum metus ipsum, a lobortis dui pharetra ut. Donec eleifend posuere nisl, sed vestibulum diam suscipit vitae. Nunc dignissim est eros, ac ornare felis sagittis vel. Nunc fringilla vestibulum volutpat. Vestibulum sagittis tempor mi, vel molestie elit interdum quis. Nulla non dignissim nibh. Suspendisse eget fringilla dolor. Sed in massa ultrices dui pellentesque consectetur sit amet ac tortor. Mauris sit amet cursus sem.</p>
        <a class="btn btn-primary btn-block">Read More</a>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <div class="post">
      <img src='img/rails1.jpg'>
      <div class="post-content">
        <h3>Lorem Ipsum</h3>
        <small>Posted by Matt on October 24, 2014</small>
        <p>Proin sit amet lectus quis ex rutrum dictum vel ut purus. In placerat lacus a nisi imperdiet varius. Donec semper suscipit odio, hendrerit sollicitudin orci ullamcorper a. Integer ornare est sed velit consectetur, fringilla tempor urna auctor. Aliquam lobortis imperdiet leo eget tincidunt. Cras blandit dapibus urna, quis commodo eros semper ut. Fusce tempus odio non commodo faucibus. Nam mattis faucibus tellus, a cursus neque accumsan fringilla. Curabitur sagittis ex vel tincidunt fermentum. Cras congue augue non gravida varius. Maecenas tincidunt dapibus elit id vulputate. Integer fermentum in risus eu tincidunt. Phasellus metus libero, elementum non rhoncus at, condimentum sed est.</p>
        <a class="btn btn-primary btn-block">Read More</a>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="post">
      <img src='img/rails1.jpg'>
      <div class="post-content">
        <h3>Lorem Ipsum</h3>
        <small>Posted by Matt on October 24, 2014</small>
        <p>Praesent ut diam dolor. Nunc ornare id velit non sodales. Fusce volutpat ante ac interdum dignissim. Morbi id lorem dignissim libero egestas dignissim vel et ex. Donec interdum metus ipsum, a lobortis dui pharetra ut. Donec eleifend posuere nisl, sed vestibulum diam suscipit vitae. Nunc dignissim est eros, ac ornare felis sagittis vel. Nunc fringilla vestibulum volutpat. Vestibulum sagittis tempor mi, vel molestie elit interdum quis. Nulla non dignissim nibh. Suspendisse eget fringilla dolor. Sed in massa ultrices dui pellentesque consectetur sit amet ac tortor. Mauris sit amet cursus sem.</p>
        <a class="btn btn-primary btn-block">Read More</a>
      </div>
    </div>
  </div>
</div>

rBlog/app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>