rBlog/config/routes.rb
Rails.application.routes.draw do
  get 'contact' => "contacts#new"

  get 'contacts/create'

  get 'about' => "about#index"

  namespace :admin do
  get 'sessions/new'
  end

  namespace :admin do
  get 'sessions/create'
  end

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
  get 'users/create'
  end

  namespace :admin do
  get 'users/edit'
  end

  namespace :admin do
  get 'users/update'
  end

  namespace :admin do
  get 'users/destroy'
  end

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'users/show'
  end

  namespace :admin do
  get 'comments/destroy'
  end

  get 'comments/new'

  namespace :admin do
  get 'categories/new'
  end

  namespace :admin do
  get 'categories/create'
  end

  namespace :admin do
  get 'categories/edit'
  end

  namespace :admin do
  get 'categories/update'
  end

  namespace :admin do
  get 'categories/destroy'
  end

  namespace :admin do
  get 'categories/index'
  end

  namespace :admin do
  get 'categories/show'
  end

  get 'categories/show'

  namespace :admin do
  get 'posts/new'
  end

  namespace :admin do
  get 'posts/create'
  end

  namespace :admin do
  get 'posts/edit'
  end

  namespace :admin do
  get 'posts/update'
  end

  namespace :admin do
  get 'posts/destroy'
  end

  namespace :admin do
  get 'posts/index'
  end

  namespace :admin do
  get 'posts/show'
  end

  get 'posts/index'

  get 'posts/show'

  resources :posts, :categories, :comments
  resources :contacts, only: [:new, :create]

  namespace :admin do
    resources :posts, :categories, :comments, :users
  end

  root 'posts#index'

end

rBlog/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts

  validates :name, presence: true
end

rBlog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

rBlog/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :users
  has_many :commnets

  validates :title,  presence: true
  validates :category_id, presence: true
  validates :body, presence: true
end

rBlog/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  
  has_many :posts

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password, confirmation: true

  def self.authentication(email, password)
    user = find_by_email(email)
    if user && user_password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

rBlog/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

rBlog/app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  def new
    @page_title = "Add Post"
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post Created"
      redirect_to admin_posts_path
    else
      render "new"
    end
  end

  def edit
    @page_title = "Edit Post"
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      flash[:notice] = "Post Updated"
      redirect_to admin_posts_path
    else
      render "new"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    flash[:notice] = "Post Removed"
    redirect_to admin_posts_path
  end

  def index
    @posts = Post.all
  end

  private

  def post_params
    params.require(:post).permit(:title, :category_id, :user_id, :tags, :img, :body)
  end
end

rBlog/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def new
    @page_title = "Add User"
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User Created"
      redirect_to admin_users_path
    else
      render "new"
    end
  end

  def edit
    @page_title = "Edit User"
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "User Updated"
      redirect_to admin_users_path
    else
      render "new"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    flash[:notice] = "User Removed"
    redirect_to admin_users_path
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

rBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rBlog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  end
end

rBlog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end
end

rBlog/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

rBlog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end
end

rBlog/app/helpers/about_helper.rb
module AboutHelper
end

rBlog/app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

rBlog/app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

rBlog/app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

rBlog/app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

rBlog/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

rBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

rBlog/app/helpers/categories_helper.rb
module CategoriesHelper
end

rBlog/app/helpers/comments_helper.rb
module CommentsHelper
end

rBlog/app/helpers/contacts_helper.rb
module ContactsHelper
end

rBlog/app/helpers/posts_helper.rb
module PostsHelper
end

rBlog/app/views/admin/users/edit.html.erb
<h2><%= @page_title %></h2>

<%= form_for [:admin, @user] do | f | %>
  <!-- Check for errors -->
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do | msg | %>
      <!-- Show errors -->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :new_password %>
    <%= f.password_field :new_password, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :new_password_confirmation %>
    <%= f.password_field :new_password_confirmation, class:"form-control" %>
  </div>
  <br>
  <%= f.submit "Submit", class:"btn btn-primary" %>
  <%= link_to "Cancel", admin_users_path, class:"btn btn-default" %>
<% end %>

rBlog/app/views/admin/users/index.html.erb
<h2 class="page-header">Manage Users <%= link_to "Create New", new_admin_user_path, class:"btn btn-success pull-right"%></h2>

<% if @users.exists? %>
  <table class="table table-striped">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Create Date</th>
      <th>Actions</th>
    </tr>
    <% @users.each do | user | %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
      <td><%= link_to "Edit", edit_admin_user_path(user), class:"btn btn-primary" %> <%= link_to "Delete", admin_user_path(user), class:"btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
</table>
<% else %>
  <p>There are no users</p>
<% end %>

rBlog/app/views/admin/users/new.html.erb
<h2><%= @page_title %></h2>

<%= form_for [:admin, @user] do | f | %>
  <!-- Check for errors -->
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do | msg | %>
      <!-- Show errors -->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class:"form-control" %>
  </div>
  <br>
  <%= f.submit "Submit", class:"btn btn-primary" %>
  <%= link_to "Cancel", admin_users_path, class:"btn btn-default" %>
<% end %>