rBlog/config/routes.rb
Rails.application.routes.draw do
  get 'contact' => "contacts#new"

  get 'contacts/create'

  get 'about' => "about#index"

  namespace :admin do
  get 'sessions/new'
  end

  namespace :admin do
  get 'sessions/create'
  end

  namespace :admin do
  get 'users/new'
  end

  namespace :admin do
  get 'users/create'
  end

  namespace :admin do
  get 'users/edit'
  end

  namespace :admin do
  get 'users/update'
  end

  namespace :admin do
  get 'users/destroy'
  end

  namespace :admin do
  get 'users/index'
  end

  namespace :admin do
  get 'users/show'
  end

  namespace :admin do
  get 'comments/destroy'
  end

  get 'comments/new'

  namespace :admin do
  get 'categories/new'
  end

  namespace :admin do
  get 'categories/create'
  end

  namespace :admin do
  get 'categories/edit'
  end

  namespace :admin do
  get 'categories/update'
  end

  namespace :admin do
  get 'categories/destroy'
  end

  namespace :admin do
  get 'categories/index'
  end

  namespace :admin do
  get 'categories/show'
  end

  get 'categories/show'

  namespace :admin do
  get 'posts/new'
  end

  namespace :admin do
  get 'posts/create'
  end

  namespace :admin do
  get 'posts/edit'
  end

  namespace :admin do
  get 'posts/update'
  end

  namespace :admin do
  get 'posts/destroy'
  end

  namespace :admin do
  get 'posts/index'
  end

  namespace :admin do
  get 'posts/show'
  end

  get 'posts/index'

  get 'posts/show'

  resources :posts, :categories, :comments
  resources :contacts, only: [:new, :create]

  namespace :admin do
    resources :posts, :categories, :comments, :users
  end

  root 'posts#index'

end

rBlog/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts

  validates :name, presence: true
end

rBlog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

rBlog/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :users
  has_many :commnets

  validates :title,  presence: true
  validates :category_id, presence: true
  validates :body, presence: true
end

rBlog/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  
  has_many :posts

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password, confirmation: true

  def self.authentication(email, password)
    user = find_by_email(email)
    if user && user_password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

rBlog/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

rBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rBlog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  end
end

rBlog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end
end

rBlog/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

rBlog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end
end

rBlog/app/helpers/about_helper.rb
module AboutHelper
end

rBlog/app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

rBlog/app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

rBlog/app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

rBlog/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

rBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

rBlog/app/helpers/categories_helper.rb
module CategoriesHelper
end

rBlog/app/helpers/comments_helper.rb
module CommentsHelper
end

rBlog/app/helpers/contacts_helper.rb
module ContactsHelper
end

rBlog/app/helpers/posts_helper.rb
module PostsHelper
end

rBlog/app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RBlog</title>
  <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin/application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="../index.html"><h1>rBlog</h1><span>/Manager</span></a>
          </div>
          <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li class="<%= params[:controller] == 'admin/posts' ? 'active' : '' %>"><%= link_to "Posts", admin_posts_path %></li>
              <li class="<%= params[:controller] == 'admin/categories' ? 'active' : '' %>"><%= link_to "Categories", admin_categories_path %></li>
              <li class="<%= params[:controller] == 'admin/users' ? 'active' : '' %>"><%= link_to "Users", admin_users_path %></li>
            </ul>
            <form class="navbar-form navbar-right search-form" role="search">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </nav>

      <section>
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <!-- Alerts & Messages -->
              <% if flash[:notice] %>
                <div class="alert alert-success"><%= flash[:notice] %></div>
              <% end %>
              <% if flash[:alert] %>
                <div class="alert alert-danger"><%= flash[:alert] %></div>
              <% end %>
              <div class="well">
                <%= yield %>
              </div>
            </div>
          </div>
        </div>
      </section>

      <footer class="text-center">
        <p>Copyright &copy; 2016, rBlog | <a href="../login.html">Admin Login</a></p>
      </footer>

      <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
      <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
      <script src="/js/bootstrap.js"></script>

</body>
</html>

rBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html"><h1>rBlog</h1></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
          </ul>
          <form class="navbar-form navbar-right search-form" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <section>
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <!-- Alerts & Messages -->
            <% if flash[:notice] %>
              <div class="alert alert-success"><%= flash[:notice] %></div>
            <% end %>
            <% if flash[:alert] %>
              <div class="alert alert-danger"><%= flash[:alert] %></div>
            <% end %>
            <%= yield %>
          </div>
          <div class="col-md-4">
            <%= render 'partials/sidebar' %>
          </div>
        </div>
      </div>
    </section>

    <%= render "partials/footer" %>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="/js/bootstrap.js"></script>
  </body>

</body>
</html>